### ISSUE TITLE
Bear benchmark triggers panic

### ISSUE THREAD

**Issue by dwlnetnl** [julienschmidt/go-http-routing-benchmark#47]
Somehow the bear test gets a nil request passed. When I dump the requests the last several tests are the following:

```
&{POST /1/events/:eventName HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/events/:eventName <nil> <nil>}
&{POST /1/push HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/push <nil> <nil>}
&{POST /1/installations HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/installations <nil> <nil>}
&{GET /1/installations/:objectId HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/installations/:objectId <nil> <nil>}
&{PUT /1/installations/:objectId HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/installations/:objectId <nil> <nil>}
&{GET /1/installations HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/installations <nil> <nil>}
&{DELETE /1/installations/:objectId HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/installations/:objectId <nil> <nil>}
&{POST /1/functions HTTP/1.1 1 1 map[] <nil> 0 [] false  map[] map[] <nil> map[]  /1/functions <nil> <nil>}
<nil>
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x489482]

goroutine 8 [running]:
testing.tRunner.func1(0xc82008a000)
    /usr/local/go/src/testing/testing.go:450 +0x171
github.com/julienschmidt/go-http-routing-benchmark.bearHandlerTest(0x0, 0x0, 0x0, 0xc8202cb4c0)
    /data01/dev/src/github.com/julienschmidt/go-http-routing-benchmark/routers.go:144 +0x1a2
github.com/ursiform/bear.(*Context).Next(0xc8202cb4c0)
    /data01/dev/src/github.com/ursiform/bear/context.go:48 +0x11e
github.com/ursiform/bear.(*Mux).ServeHTTP(0xc8202b64e0, 0x7fb2acef7e08, 0xc8202cc420, 0xc82010a380)
    /data01/dev/src/github.com/ursiform/bear/mux.go:138 +0x19d
github.com/julienschmidt/go-http-routing-benchmark.TestRouters(0xc82008a000)
    /data01/dev/src/github.com/julienschmidt/go-http-routing-benchmark/routers_test.go:73 +0x52a
testing.tRunner(0xc82008a000, 0x10f3620)
    /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xe47108, 0x10f3620, 0x1, 0x1, 0x42ca01)
    /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820167ee8, 0x0)
    /usr/local/go/src/testing/testing.go:494 +0x70
main.main()
    github.com/julienschmidt/go-http-routing-benchmark/_test/_testmain.go:888 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
exit status 2
FAIL    github.com/julienschmidt/go-http-routing-benchmark  0.044s
```

**Comment by arekkas** [comment]
+1

**Comment by beauhoyt** [comment]
+1

**Comment by Annonomus-Penguin** [comment]
+1

**Comment by de3** [comment]
+1

**Comment by cmpis** [comment]
I got the same error, but commenting out bear didn't work. I did comment out all the routers in router_test.go and for some reason all the benchmarks started running.

I don't know enough go nor enough about these tests to understand why they're still running when they've been commented out.

I'm gonna try to figure out which one is causing the panic for me.

**Comment by cmpis** [comment]
Yea it does seem to be Bear for me too after I disable the rivet tests so I can at least compile

**Comment by dc0d** [comment]
+1

**Comment by julienschmidt** [comment]
This seems to have been resolved upstream in the meantime
